#ifndef ATSAME54_XPLAINED_API_XPLAINED_IO_PDEC_H_
#define ATSAME54_XPLAINED_API_XPLAINED_IO_PDEC_H_

/**
 * @brief 
 */
void Xplained_PDEC_Initialize(void);

#endif  // ATSAME54_XPLAINED_API_XPLAINED_IO_PDEC_H_
