name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/c4deszes/arm-gcc-docker:v1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Configure
        run: |
          cmake --preset=armgcc-unix-release .

      - name: Build
        run: |
          cmake --build --preset=armgcc-unix-release-example
