name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  example:
    name: Example
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/c4deszes/arm-gcc-docker:v1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Configure build
        run: |
          cmake --preset=armgcc-unix-release .

      - name: Build example
        run: |
          cmake --build --preset=armgcc-unix-release-example

  unittest:
    name: Unit test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/c4deszes/arm-gcc-docker:v1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Configure build
        run: |
          cmake --preset=gcc-debug .

      - name: Run unit tests
        run: |
          ctest --preset=gcc-gtest-unittest
