name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  cpplint:
    name: cpplint
    runs-on: ubuntu-latest
    container:
      image: python
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install cpplint

      - name: Lint using Cpplint
        run: cpplint --recursive atsame54-hal atsame54-xplained atsame54-example
